#!/bin/bash

#
# From this point on, we are arch-chrooted into the new system
#
echo "-> Configuring /etc/systemd/journald.conf"
sed -i 's/Storage=volatile/#Storage=auto/' /etc/systemd/journald.conf

echo "-> Removing presumptuous dhcpcd udev rules"
rm /etc/udev/rules.d/81-dhcpcd.rules

echo "-> Disabling archiso systemd services"
systemctl disable pacman-init.service choose-mirror.service
rm -r /etc/systemd/system/{choose-mirror.service,pacman-init.service}
rm -r /etc/systemd/system/{etc-pacman.d-gnupg.mount,getty@tty1.service.d}
rm /etc/systemd/scripts/choose-mirror

echo "-> Removing archiso scripts"
rm /etc/systemd/system/getty@tty1.serivice.d/autologin.conf
rm /root/{.automated_script.sh,.zlogin}
rm /etc/mkinitcpio-archiso.conf
rm -r /etc/initcpio

echo "-> Importing archlinux master keys"
pacman-key --init
pacman-key --populate archlinux

echo "-> Setting /etc/localtime: $region/$city"
ln -sf /usr/share/zoneinfo/$region/$city /etc/localtime

echo "-> Setting the hardware clock"
hwclock --systohc

echo "-> Setting locale"
sed -i 's/#en_US\.UTF-8/en_US.UTF-8/' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

echo "-> Setting /etc/hostname: $host"
echo $host > /etc/hostname
