#!/bin/bash
set -e

reset="\e[0m"
bold="\e[1m"
bold_green="\e[1;92m"
bold_cyan="\e[1;96m"
bold_white="\e[1;99m"

echo_milestone()
{
    echo -e "$bold_green==>$reset $bold_white$1$reset"
}

echo_task()
{
    echo -e "  $bold_cyan->$reset $bold_white$1$reset"
}

#
# Args passed from sysinit
#
region=$1
city=$2
host=$3

#
# From this point on, we are arch-chrooted into the new system
#
echo_milestone "Cleaning up artifacts from the live environment"
echo_task "Configuring /etc/systemd/journald.conf"
sed -i 's/Storage=volatile/#Storage=auto/' /etc/systemd/journald.conf

echo_task "Removing presumptuous dhcpcd udev rules"
rm -f /etc/udev/rules.d/81-dhcpcd.rules

echo_task "Disabling archiso systemd services"
systemctl disable pacman-init.service choose-mirror.service > /dev/null
rm -rf /etc/systemd/system/{choose-mirror.service,pacman-init.service}
rm -rf /etc/systemd/system/{etc-pacman.d-gnupg.mount,getty@tty1.service.d}
rm -f /etc/systemd/scripts/choose-mirror

echo_task "Removing archiso scripts"
rm -f /etc/systemd/system/getty@tty1.serivice.d/autologin.conf
rm -f /root/{.automated_script.sh,.zlogin}
rm -f /etc/mkinitcpio-archiso.conf
rm -rf /etc/initcpio

echo_milestone "Importing archlinux master keys"
pacman-key --init
pacman-key --populate archlinux

echo_milestone "Configuring locale"
sed -i 's/#en_US\.UTF-8/en_US.UTF-8/' /etc/locale.gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
locale-gen > /dev/null

echo_milestone "Configuring time"
echo_task "Setting /etc/localtime: $region/$city"
ln -sf /usr/share/zoneinfo/$region/$city /etc/localtime

echo_task "Setting the hardware clock"
hwclock --systohc

echo_milestone "Configuring network"
echo_task "Setting /etc/hostname: $host"
echo $host > /etc/hostname
