#!/bin/bash

reset="\e[0m"
bold="\e[1m"
red="\e[31m"
green="\e[32m"
yellow="\e[33m"
cyan="\e[36m"
white="\e[97m"

bold_red="\e[1;31m"
bold_green="\e[1;32m"
bold_yellow="\e[1;33m"
bold_cyan="\e[1;36m"
bold_white="\e[1;39m"

echo_bold_red()
{
    echo -e "$bold_red$1 $reset"
}

echo_bold_green()
{
    echo -e "$bold_green$1 $reset"
}

echo_bold_yellow()
{
    echo -e "$bold_yellow$1 $reset"
}

echo_bold_cyan()
{
    echo -e "$bold_cyan$1 $reset"
}

echo_bold_white()
{
    echo -e "$bold_white$1 $reset"
}

echo_error()
{
    echo "ERROR: $1"
    echo_usage
    exit 1
}

device=""
city="Chicago"
boot="bios"
host="dev"
label="msdos"
fs="ext4"
region="America"

short_opts="b:d:p:f:c:n:h"
long_opts="boot:,disk:,part-label:,fs:,city:,name:,help,uefi"

echo_usage()
{
    echo "Usage:"
    echo "  sysinit -b | --boot <boot> -d | --disk <disk> [options]"
    echo ""
    echo "Overview:"
    echo "  Initialize the Arch Linux system using /dev/<disk> as the device"
    echo "  for the root filesystem. The device will be formatted with a new"
    echo "  partition label and filesystem. If <boot> is uefi, then a FAT"
    echo "  partition /boot will be made for the EFI partition. Otherwise, "
    echo "  only one partition, /, will be created."
    echo ""
    echo "Options:"
    echo "  -b, --boot         uefi | bios (default: $boot)"
    echo "  -p, --part-label   gpt | msdos (default: $label)"
    echo "  -f, --fs           flesystem type (default: $fs)"
    echo "  -c, --city         city for timezone (default: $city)"
    echo "  -n, --name         hostname (default: $host)"
    echo "  -h, --help         print this help"
    echo ""
}

ckopt_boot()
{
    case "$boot" in
        u|uefi|U|UEFI) boot=uefi;;
        b|bios|B|BIOS) boot=msdos;;
        *) echo_error "unsupported boot type: $boot" && exit;;
    esac
}

ckopt_label()
{
    case "$label" in
        g|gpt|G|GPT) label=gpt;;
        m|msdos|M|MSDOS) label=msdos;;
        *) echo_error "unsupported partition label: $label" && exit;;
    esac

    if [[ $label == "gpt" && $boot != "uefi" ]]; then
        echo_error "UEFI must be used with a GPT label" && exit;;
    fi
}

#
# Verify cli arguments
#
options=$(getopt -o $short_opts -l $long_opts -- "$@")
if [[ $? -ne 0 ]]; then
    echo_error "invalid options"
    echo_usage
    exit 1
fi

eval set -- "$options"
while true; do
    case "$1" in
        -b|--boot) boot="$2";;
        -p|--part-label) label="$2";;
        -f|--fs) fs="$2";;
        -c|--city) city="$2";;
        -n|--name) host="$2";;
        -d|--device) device="/dev/$2";;
        -h|--help) echo_usage && exit;;
        --) break;;
        *) echo_error "unknown option: $1";;
    esac
    shift 2
done

ckopt_boot
ckopt_label

#
# Display banner
#
echo "  ___           _       _     _                   ";
echo " / _ \         | |     | |   (_)                  ";
echo "/ /_\ \_ __ ___| |__   | |    _ _ __  _   ___  __ ";
echo "|  _  | '__/ __| '_ \  | |   | | '_ \| | | \ \/ / ";
echo "| | | | | | (__| | | | | |___| | | | | |_| |>  <  ";
echo "\_| |_/_|  \___|_| |_| \_____/_|_| |_|\__,_/_/\_\ ";
echo "                                                  ";

#
# Confirm installation parameters
#
echo_bold_cyan "Installation Parameters:"
echo -n "  - rootfs device: " && echo_bold_white "$device"
echo -n "  - rootfs type: " && echo_bold_white "$fs"
echo -n "  - rootfs partition label: " && echo_bold_white "$label"
echo -n "  - boot type: " && echo_bold_white "$boot"
echo -n "  - timezone city: " && echo_bold_white "$city"
echo -n "  - hostname: " && echo_bold_white "$host"

echo -ne "$bold_yellow"
echo -ne "Format $device with new $label? [y/n]: $reset"
read -N 1 format
echo ""

if [[ $format != "y" ]]; then
    echo_bold_white "Format cancelled...exiting"
    exit 1
fi

echo "-> Updating the system clock"
timedatectl set-ntp true

#
# Format the device
#
echo "-> Formatting $device with $label"
parted -s $device mklabel $label

begin="2MiB"
end="512MiB"
parted -s $device mkpart primary $begin $end
parted -s $device set 1 boot on

begin=$end
end="100%"
parted -s $device mkpart primary $begin $end
parted -s $device set 2 root on

#
# Create and mount filesystems
#
case $boot in
msdos)
    local part=$(lsblk -lpo NAME | grep $device | head -2 | tail -1)

    echo "-> Creating the root $fs filesystem on $part"
    mkfs.$fs $part

    echo "-> Mounting $part onto /mnt"
    mount $part /mnt
    ;;
uefi)
    local boot_part=$(lsblk -lpo NAME | grep $device | head -2 | tail -1)
    local root_part=$(lsblk -lpo NAME | grep $device | head -3 | tail -1)

    echo "-> Creating the root $fs filesystem on $root_part"
    mkfs.$fs $root_part

    echo "-> Creating the boot vfat filesystem on $boot_part"
    mkfs.vfat $boot_part

    echo "-> Mounting $root_part onto /mnt"
    mount $root_part /mnt

    echo "-> Mounting $boot_part onto /mnt/boot"
    mount $boot_part /mnt/boot
    ;;
*)
    echo_error "invalid boot type: $boot"
    exit
    ;;
esac

#
# Copy the root filesystem to /mnt
#
echo -n "-> Copying the archiso to /mnt..."
cp -ax / /mnt
echo "done"

echo -n "-> Copying the kernel to /mnt/boot..."
cp -aT \
    /run/archiso/bootmnt/arch/boot/$(uname -m)/vmlinuz \
    /mnt/boot/vmlinuz-linux
echo "done"

echo "-> Generating /etc/fstab"
genfstab -U /mnt >> /mnt/etc/fstab

echo "-> Chrooting into the new system"
arch-chroot /mnt /root/sysinit-chroot
